### ISSUE TITLE
Color configuration not working

### ISSUE THREAD

**Issue by grantcarthew** [couchand/lines-js#1]
Hi,

I'm trying to use this package on the console and the color configuration below does not work:

```js

const t = lines()
t.line({
  from: [0, 0],
  to: [4, 0],
  style: 'bold',
  color: {
    foreground: 'red'
  }
})
t.line({
  from: [2, 0],
  to: [2, 3],
});


```

I think the ansi-styles package has changed.

Error is as follows:

```sh

/home/grant/node-console-probe/node_modules/lines-js/lib/color.js:17
          if (color in style.color) {
                    ^

TypeError: Cannot use 'in' operator to search for 'red' in undefined
    at Object.foreground (/home/grant/node-console-probe/node_modules/lines-js/lib/color.js:17:21)
    at /home/grant/node-console-probe/node_modules/lines-js/lib/lines.js:142:38
    at Array.map (<anonymous>)
    at /home/grant/node-console-probe/node_modules/lines-js/lib/lines.js:134:23
    at Array.map (<anonymous>)
    at Lines.toString (/home/grant/node-console-probe/node_modules/lines-js/lib/lines.js:133:27)
    at Object.<anonymous> (/home/grant/node-console-probe/console-probe.js:32:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

**Comment by couchand** [comment]
Oh wow, thanks for finding this!  It looks like `ansi-styles` chose to unpublish version 2.2.0, which is what I'd developed against here (see https://github.com/chalk/ansi-styles/issues/15#issuecomment-202589714)

Upgrading to 3 fixes it, so I'll publish a new version now.
